### ISSUE TITLE
Install Lucid - icon

### ISSUE THREAD

**Issue by Devollox** [Devollox/TaskBoardOld#27]
Установить Lucid - icon через ```npm``` .  lucide-react и просто lucide

**Comment by 3ldan** [comment]
Not sure exactly what the issue is but I have linked to both libraries on NPM:

1. https://www.npmjs.com/package/lucide
2. https://www.npmjs.com/package/lucide-react

**Comment by Devollox** [comment]
I'm checking the site for functionality)
